number = [1 ,2 ,3 ,4]
print (number[1])
number.append([100])
print(number)
number.remove(2)
print(number)
a = number.pop(3)
print(a)
number.extend([1 ,2, 3])
print(number)
number[0]=75
print(number)
b = number.count(1)
print(b)
c = len(number)
print(c)
number.insert(1,1000)
print(number)
d = number.index(2)
print(d)
number.reverse()
print(number)